### ISSUE TITLE
ggflexsurvplot removing groups from KM plot

### ISSUE THREAD

**Issue by andersbergren** [kassambara/survminer#408]
ggflexsurvplot() should show the KM curve with model fit curves for all strata. Instead the strata for the KM curve have been relabelled "All".

May be related to the length(summary(fit)) check that should only relabel strata to "All" if if the summary list length equals 1.

Here you can see my model fit curves and and the broken red "All" KM curve which should be broken out by strata.

![image](https://user-images.githubusercontent.com/7705573/60992571-bdc82b00-a31a-11e9-8d3c-9c1421a10174.png)

**Comment by andersbergren** [comment]
Seems related to this code in the function:
`   isfac <- .is_all_covariate_factor(fit)
   if(!all(isfac)){
     .formula <- .build_formula(surv.obj, "1")
     n.strata <- 1
   }`
It creates a vector that's not a factor, then checks if that vector is a factor. Always returning false I believe.

**Comment by andersbergren** [comment]
Result when check is removed
![image](https://user-images.githubusercontent.com/7705573/61147385-38738080-a4aa-11e9-9ad4-cdef8500dbf3.png)

**Comment by kassambara** [comment]
`ggflexsurvplot()`  expected the grouping variable to be strictly a factor for showing grouped KM. 

fixes: now, the grouping variable can be either a factor or a character vector (in your example).

Should work now, thanks!

You can install the latest dev version as follow: 

```r
devtools::install_github("kassambara/survminer", build_vignettes = FALSE, dependencies = FALSE)
```

**Comment by jumbanhounc** [comment]
I'm still getting this problem.  I think the problem is in the function `is_factor_or_character` has:
'is.facet(x) | is.character(x)`
and should be
'is.factor(x) | is.character(x)`

**Comment by igutermes** [comment]
The issue sting lingers. 

Just in case anyone is still stuck in this problem, just use a `as.character()` in your model and the function will work as expected.

**Comment by kassambara** [comment]
Thanks for the clear report and for pinpointing the `is.facet` typo!

This is fixed in the current dev version (0.5.2.999) — `ggflexsurvplot()` now correctly detects a factor (or character) grouping covariate instead of collapsing every stratum into a single "All" curve.

Confirmation reprex against the dev version:

```r
library(survminer)
library(survival)
library(flexsurv)

# FACTOR grouping covariate (previously collapsed to a single "All" stratum)
lung2 <- lung
lung2$sex <- factor(lung2$sex, levels = c(1, 2), labels = c("Male", "Female"))

fit <- flexsurv::flexsurvreg(Surv(time, status) ~ sex, data = lung2,
                             dist = "weibull")

p <- ggflexsurvplot(fit)
levels(p$data.survplot$strata)
#> [1] "sex=Male"   "sex=Female"
p
```

The plot now shows both strata (Male and Female), each with its own Kaplan-Meier step curve and matching flexsurv model fit, rather than one merged red "All" curve.

Install the dev version:

```r
remotes::install_github("kassambara/survminer")
```
