### ISSUE TITLE
ggcoxzph(): Incorrect Plot for transform="log"

### ISSUE THREAD

**Issue by MetzgerSK** [kassambara/survminer#454]
It appears that `ggcoxzph()` does not display the appropriate Schoenfeld graph when the time transform is ln(_t_).  Instead, it reproduces the Schoenfeld graph for _t_.  As a secondary consequence of the display issue, the smoothed fit curve does not span the entire x-axis range for the ln(_t_) graph.

I took a very quick look at the function's code, to ensure I wasn't forgetting to specify an option.  It doesn't look like it, from what I can tell.  From what I'm seeing, it looks like this chunk may be involved:

```{r}
if (x$transform == "log") {
      xx <- exp(xx)
      pred.x <- exp(pred.x)
}
```

For a MWE:
```{r}
library(survival)
library(survminer)
data("lung")

# Estimate the model
mod <- coxph(Surv(time, status) ~ sex + age, data = lung)

# Run the PH tests
ph.t <- cox.zph(mod, transform="identity")
ph.lnT <- cox.zph(mod, transform="log")

# check plots for transform = t
plot(ph.t)
ggcoxzph(ph.t, resid=TRUE, se=FALSE)
    # ALL MATCH

# check plots for transform = ln(t)
## ggcoxzph plot matches the previous one, but
## should match the plots from the subsequent plot() call
ggcoxzph(ph.lnT, resid=TRUE, se=FALSE)
plot(ph.lnT)
    # DON'T MATCH

# (checked km, rank for plot() vs. ggcoxzph(): all those plots match)


# Checking to see if the root cause is indeed related to the
# transform attribute, with the transform-specific if/elses in
# ggcoxzph()
#
# If we force-remove the transform attribute, does
# ggcoxzph perform more as expected for ln(t)?

ph.lnT.fake <- ph.lnT
attr(ph.lnT.fake, "transform") <- ""
ggcoxzph(ph.lnT.fake, resid=TRUE, se=FALSE) 
    # It would appear so.  (Hard to confirm definitively
    # from the plot, with the difference between the x-axis 
    # scales from plot() and ggcoxzph() when t is log-transformed.)
```

**Comment by Generalized** [comment]
Tell me, please, what is the current status of this issue? Is this fixed in the newer releases? @MetzgerSK

**Comment by MetzgerSK** [comment]
I reran the MWE just now under `survminer 0.4.9` and the issue still persists.  

The chunk of code I mentioned initially does end up being involved, but indirectly.  The culprit lines appear to be `ggcoxzph`'s lines 71-75:
```
else if (x$transform == "log") {
            gplot <- gplot + geom_line(aes(x = log(pred.x), 
                y = yhat)) + xlab("Time") + ylab(ylab[i]) + 
                ylim(yr)
        }
```

I can replicate `plot.cox.zph`'s `transform="log"` output perfectly with `ggcoxzph` if I modify the lines in question to read
```
else if (x$transform == "log") {
            gplot <- gplot + geom_line(aes(x = pred.x,       # REMOVED LOG TRANSF
                y = yhat)) + xlab("Time") + ylab(ylab[i]) + 
                ylim(yr) + scale_x_continuous(trans='log10') # SCALED X-AXIS W/LOG TRANSF
        }		
```

**Comment by kassambara** [comment]
Fixed in the development version (0.5.2.999) — merged via #740.

With `cox.zph(transform = "log")`, `ggcoxzph()` was drawing the fitted line at `log(pred.x)` while the residual points and the confidence bands were on the original time scale — so the fit line was squeezed to the far left, misaligned with the data. The fit line now uses the same scale as the points, and the x-axis is log-scaled (`scale_x_log10()`), matching `survival::plot.cox.zph(log = "x")`.

```r
# remotes::install_github("kassambara/survminer")   # dev 0.5.2.999
library(survminer); library(survival)
fit <- coxph(Surv(time, status) ~ age + sex, data = lung)
ggcoxzph(cox.zph(fit, transform = "log"))
```

The smooth fit and its confidence band now span the full (log) time axis, aligned with the Schoenfeld residuals:

![ggcoxzph transform = log fixed](https://i.imgur.com/72aG0RV.png)
